### PR TITLE
Multiple parameters with the same name

### LINKED ISSUE #36: Multiple params with the same name?
Is it possible to do something like this:

myprogram -p foo -p bar -p baz

and be able to get all three -p parameter values? When I try I can only get the first one.

### PR DESCRIPTION
**Pull request by ddovod**
Hi. Thank you very much for working on this awesome library! I'm having pleasure using it.
Please consider this fix which fixes #36 .
With this patch you'll be able to pass multiple parameters with the same name and work with a subset of parameters like this:
```
// app --foo=value1 --foo=value2 --foo=value3
auto fooArgsCounr = args.params("foo").size();  // 3
for (const auto& params : args.params("foo")) {
    // iterate over "foo" params and "value1", "value2" and "value3" values
}
```
Thanks in advance!

### CODE REVIEW

**Comment by adishavit** [comment]
Sorry for the delay in response - I've been busy in these crazy times.
This is an interesting feature - I want to review how it interacts with the rest of the API.
I'll get around to it as soon as I can.

**Comment by adishavit** [comment]
Nice solution! I merged the PR.
Do you want to update the `readme` to explain this?

**Comment by ddovod** [comment]
Sure, thanks!
I can create a new PR in a few days, but if you want to fix readme yourself, please go ahead

**Comment by adishavit** [comment]
Done. Updated.
I also add stripping of leading dashes.

But it got me thinking - some things are still missing:

1. Support for initializer list of synonyms;
2. Accessing via `operator()`

To solve (1) you would need to combine the results from several ipper/lower bound runs, so no more returning of iterator references (in C++20 we could use lazy coroutines for this, but we're with C++11.

I'm thinking maybe replace your custom class with a pushing the values into a stringstream as happens with the regular `operator()` - separated with `\n`. Using `std::getline()` will then generically get everything in order and with only a tiny change to the existing interface.

**Pull request merged**
